version: '3'
services:
  bot:
    build: ../..
    container_name: Steam_Wishlist_Bot
    restart: always
    command: python main.py
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
