version: '3.8'
services:
  bot:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    container_name: Steam_Wishlist_Bot
    restart: always
    volumes:
      - ../TelegramBot:/app/TelegramBot
      - ../SteamAPI:/app/SteamAPI
    command: python /app/TelegramBot/main.py
    environment:
      - PYTHONUNBUFFERED=1
